### ISSUE TITLE
Release v2 in this repo

### ISSUE THREAD

**Issue by tricki** [stencil-community/stencil-router#126]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

Update this repo with the newer router in [`stencil-router-v2`](https://github.com/ionic-team/stencil-router-v2/) and release version 2.

**Comment by DominikPieper** [comment]
Prepared a PR https://github.com/stencil-community/stencil-router/pull/141 for that
